First draft of Personal Applications
run-ai/docs pull request #1316
Opened 2024-12-19 14:39 UTC by SherinDaher-Runai

2024-12-19 14:46 UTC, ozRunAI requested changes

2024-12-19 14:46 UTC, ozRunAI commented on docs/Researcher/best-practices/personal-applications.md
> +Applications are used for API integrations with Run:ai. An application contains a client secret. Using the client key you can obtain a token and use it within subsequent API calls.
```suggestion
Applications are used for API integrations with Run:ai. An application contains a client ID and a client secret. Using the client credentials you can obtain a token and use it within subsequent API calls.
```

2024-12-19 14:46 UTC, ozRunAI commented on docs/admin/authentication/applications.md
> +Applications are used for API integrations with Run:ai. An application contains a client secret. With the client secret you can obtain a token and use it within subsequent API calls.
```suggestion
Applications are used for API integrations with Run:ai. An application contains a client key and secret. Using the client credentials you can obtain a token and use it within subsequent API calls.
```

2024-12-19 14:46 UTC, ozRunAI commented on docs/Researcher/best-practices/personal-applications.md
> +# Personal Applications
I'm not sure we would like to promote it in this name - Maybe User Applications? not sure

2024-12-23 16:28 UTC, ozRunAI requested changes

2024-12-23 16:28 UTC, ozRunAI commented on docs/Researcher/best-practices/user-applications.md
> +Applications are used for API integrations with Run:ai. An application contains a client ID and a client secret. With the client credentials you can obtain a token and use it within subsequent API ca
link to https://docs.run.ai/latest/developer/rest-auth/ ?

2024-12-23 16:28 UTC, ozRunAI commented on docs/Researcher/best-practices/user-applications.md
> +## Creating Personal Applications
```suggestion
## Creating Applications
```

2024-12-24 12:47 UTC, ozRunAI requested changes

2024-12-24 12:47 UTC, ozRunAI commented on docs/developer/rest-auth.md
>          }
reqUrl = "https://cp-590d-run-13764-kc-upgrade.runailabs.com/api/v1/token"
?!

2024-12-24 12:47 UTC, ozRunAI commented on docs/developer/rest-auth.md
>            "grantType":"app_token",
'https://<runai_url>/api/v1/token' \

2024-12-29 17:35 UTC, ozRunAI requested changes

2024-12-30 18:09 UTC, SherinDaher-Runai commented on docs/developer/user-applications.md
> +    User applications are supported in cluster version 2.20 and above.
Keep note as is

2024-12-30 18:09 UTC, SherinDaher-Runai commented on docs/developer/user-applications.md
> +Applications are used for API integrations with Run:ai. An application contains a client ID and a client secret. With the client credentials, you can obtain a token as detailed in [API authentication
Updated

2024-12-31 10:41 UTC, ozRunAI approved these changes

2024-12-31 11:38 UTC, merged