V2.16-RUN-14155-Expose-GPU-health
run-ai/docs pull request #612
Opened 2023-12-27 11:41 UTC by jasonnovichRunAI

2023-12-27 17:39 UTC, lavianalon commented on docs/admin/admin-ui-setup/dashboard-analysis.md
> +* **Total GPU/CPU Nodes**&mdash;indicates the number of nodes configured to work with the platform.
I would use "sum total of nodes in all clusters connected to the platform" instead of "number of nodes configured to work with the platform

2023-12-27 17:42 UTC, lavianalon commented on docs/admin/admin-ui-setup/dashboard-analysis.md
> +* **Total GPUs/CPUs**&mdash;indicates the total number of GPUs or CPUs configured to work with the platform.
The total number of GPUs/CPUs in all clusters connected to the platform

2023-12-27 17:44 UTC, lavianalon commented on docs/admin/admin-ui-setup/dashboard-analysis.md
> +The *Free GPUs* graph displays the number of nodes and how many GPUs or CPUs are configured in each node.
displays the number of free GPUs/CPUs on each node

2023-12-27 17:44 UTC, lavianalon requested changes
see comments

2023-12-29 10:35 UTC, jasonnovichRunAI commented on docs/admin/admin-ui-setup/dashboard-analysis.md
> +The *Free GPUs* graph displays the number of nodes and how many GPUs or CPUs are configured in each node.
```suggestion
The *Free GPUs* graph displays the number of free GPUs or CPUs on each node.
```

2023-12-29 10:37 UTC, jasonnovichRunAI commented on docs/admin/admin-ui-setup/dashboard-analysis.md
> +* **Total GPU/CPU Nodes**&mdash;indicates the number of nodes configured to work with the platform.
```suggestion
* **Total GPU/CPU Nodes**&mdash;the total number of GPUs or CPUs in all the clusters that are connected to the platform.
```

2023-12-29 10:49 UTC, jasonnovichRunAI commented on docs/admin/admin-ui-setup/dashboard-analysis.md
> +* **Total GPU/CPU Nodes**&mdash;indicates the number of nodes configured to work with the platform.
```suggestion
* **Total GPU/CPU Nodes**&mdash;indicates the sum total of nodes in all clusters connected to the platform.
```

2023-12-29 10:50 UTC, jasonnovichRunAI commented on docs/admin/admin-ui-setup/dashboard-analysis.md
> +* **Total GPUs/CPUs**&mdash;indicates the total number of GPUs or CPUs configured to work with the platform.
```suggestion
* **Total GPUs/CPUs**&mdash;indicates ihe total number of GPUs/CPUs in all the clusters that are connected to the platform.
```

2023-12-29 10:52 UTC, jasonnovichRunAI commented
@lavianalon implemented and merged.

2023-12-29 10:52 UTC, merged