reorder self-hosted docs
run-ai/docs pull request #716
Opened 2024-03-17 12:09 UTC by ozRunAI

…lm values, added section how to use custom docker registry credentials

2024-03-17 12:12 UTC, ozRunAI commented
@jasonnovichRunAI we need it to be merged for 2.13-2.17

2024-03-17 12:22 UTC, jasonnovichRunAI commented on docs/admin/runai-setup/self-hosted/k8s/backend.md
> +Create the secret named `runai-reg-creds` based on your existing credentials as explained [here](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-
@ozRunAI we try not to use the word [here] with a link.
```suggestion
Create the secret named `runai-reg-creds` based on your existing credentials. For more information, see [Create a Secret based on existing credentials](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials){target=_blank}.
```

2024-03-17 12:22 UTC, jasonnovichRunAI commented on docs/admin/runai-setup/self-hosted/k8s/backend.md
> +To access the organization's docker registry it is required to set the registry's credentials (imagePullSecret)
@ozRunAI missing period at the end of the sentence.
```suggestion
To access the organization's docker registry it is required to set the registry's credentials (imagePullSecret).
```

2024-03-17 12:24 UTC, jasonnovichRunAI commented on docs/admin/runai-setup/self-hosted/k8s/backend.md
> +#### Helm values
@ozRunAI is this supposed to be a H4? Maybe you meant an H3?
```suggestion
### Helm values
```

2024-03-17 12:27 UTC, jasonnovichRunAI commented on docs/admin/runai-setup/self-hosted/ocp/backend.md
> +#### Helm values
@ozRunAI, same as above.

2024-03-17 12:27 UTC, jasonnovichRunAI commented on docs/admin/runai-setup/self-hosted/ocp/backend.md
> +To access the organization's docker registry it is required to set the registry's credentials (imagePullSecret)
@ozRunAI same as above.

2024-03-17 12:27 UTC, jasonnovichRunAI commented on docs/admin/runai-setup/self-hosted/ocp/backend.md
> +Create the secret named `runai-reg-creds` based on your existing credentials as explained [here](https://docs.openshift.com/container-platform/latest/openshift_images/managing_images/using-image-pull
@ozRunAI same as above.

2024-03-17 13:14 UTC, jasonnovichRunAI commented on docs/admin/runai-setup/self-hosted/k8s/backend.md
> +### Domain certificate
@ozRunAI needs a line between headings

```suggestion

### Domain certificate
```

2024-03-17 13:15 UTC, jasonnovichRunAI commented on docs/admin/runai-setup/self-hosted/k8s/backend.md
>  ### Connect to Run:ai User Interface
```suggestion

### Connect to Run:ai User Interface
```

2024-03-20 06:55 UTC, yarongol requested changes

2024-03-20 10:44 UTC, merged