shaibi/RUN 16065
run-ai/docs pull request #749
Opened 2024-04-07 09:34 UTC by gshaibi

- **Update cluster installation instructions and troubleshooting**
- **.**

2024-04-07 13:32 UTC, roir approved these changes

2024-04-08 10:47 UTC, ozRunAI requested changes

2024-04-08 10:47 UTC, ozRunAI commented on docs/admin/runai-setup/cluster-setup/cluster-prerequisites.md
>      * To use [Dynamic MIG](../../../Researcher/scheduling/fractions.md#dynamic-mig), the GPU Operator must be installed with the flag `mig.strategy=mixed`. If the GPU Operator is already installed, e
I think its relevant

2024-04-08 10:47 UTC, ozRunAI commented on docs/admin/troubleshooting/cluster-health-check.md
> +1. Check the message in the UI for further details regarding the missing prerequisites.
do not use the word UI

2024-04-08 10:47 UTC, ozRunAI commented on docs/admin/troubleshooting/cluster-health-check.md
> +## Advanced Troubleshooting
```suggestion
## Advanced troubleshooting
```

2024-04-08 10:47 UTC, ozRunAI commented on docs/admin/troubleshooting/cluster-health-check.md
> +kubectl get cm runai-public -oyaml | yq .data.runai-public
should we use yq also here? is it necessary in this example?

2024-04-08 10:47 UTC, ozRunAI commented on docs/admin/troubleshooting/cluster-health-check.md
> +### Resources not deployed / System Unavailable / Reconciliation Failed
```suggestion
### Resources not deployed / System unavailable / Reconciliation failed
```

2024-04-08 11:57 UTC, ozRunAI approved these changes

2024-04-08 12:03 UTC, jasonnovichRunAI commented on docs/admin/runai-setup/cluster-setup/cluster-prerequisites.md
> +!!! Notes
```suggestion
!!! Note
```

2024-04-08 12:06 UTC, merged