RUN-16860-added-info-for-editing-and-viewing
run-ai/docs pull request #821
Opened 2024-06-18 13:38 UTC by JamieWeider72

2024-06-18 14:05 UTC, jasonnovichRunAI requested changes
@JamieWeider72 in the section with "Step 1: UI configuration". in step 3 there are only 2 choices, but you added a 3rd and did update the procedure.

2024-06-19 08:33 UTC, gal-revach reviewed
@JamieWeider72 please see my comments

2024-06-19 08:33 UTC, gal-revach commented on docs/admin/runai-setup/authentication/sso.md
>  Before using OpenShift, first define OAuthClient to control various aspects of the OAuth flow, such as redirect URIs and authentication methods to ensure secure and approprpriate access to resources.
```suggestion
Before using OpenShift, first define OAuthClient. The OAuth client interacts with OpenShift’s OAuth server to authenticate users and request access tokens.
```

2024-06-19 08:33 UTC, gal-revach commented on docs/admin/runai-setup/authentication/sso.md
>  1. Create a new ```OAuthClient``` Kubernetes object with the following content
```suggestion
1. Create a new ```OAuthClient``` Kubernetes object with the following content. 
Replace the `<runai_env_url>` with the URL of your Run:ai platform.
Replace `my-client` and `this-is-my-secret` with client name and secret you choose.
```

2024-06-19 08:33 UTC, gal-revach commented on docs/admin/runai-setup/authentication/sso.md
>          1. In the `Discovery URL` field, enter the discovery URL .
```suggestion
        1. In the `Base URL` field, enter you OpenShift Base URL (https://api.<your-openshift-domain>:6443).
```

2024-06-19 10:17 UTC, gal-revach approved these changes

2024-06-19 13:31 UTC, merged