Fixes cluster upgrade
run-ai/docs pull request #865
Opened 2024-07-11 10:32 UTC by ozRunAI

2024-07-11 10:43 UTC, ozRunAI commented
@jasonnovichRunAI please merge to 2.17 as well

2024-07-17 08:05 UTC, JamieWeider72 requested changes

2024-07-17 08:05 UTC, JamieWeider72 commented on docs/admin/runai-setup/cluster-setup/cluster-upgrade.md
> +* Select the cluster you wish to upgrade.
```suggestion
* Select the cluster you want to upgrade.
```

2024-07-17 08:05 UTC, JamieWeider72 commented on docs/admin/runai-setup/cluster-setup/cluster-upgrade.md
> +* In case of a failure, see the [Installation troubleshooting guide](../../troubleshooting/troubleshooting.md#installation).
```suggestion
* In the case of a failure, refer to the [Installation troubleshooting guide](../../troubleshooting/troubleshooting.md#installation).
```

2024-07-17 08:06 UTC, JamieWeider72 approved these changes

2024-07-17 08:06 UTC, merged